### PR TITLE
Create a genres table and a genre movie table with relations as reque…

### PR DESCRIPTION
**Pull request by robertahagg**
Hi Axel.
I have now finished my part of the group assignment for the imdb clone. Please confirm if I have been approved.

### CODE REVIEW

**Comment by robertahagg** [comment]
Please go ahead and merge when approved. Thank you

**Comment by axeberg** [comment]
@robertahagg Tables look good, what about the models? And don't forget you're also added to the #102 issue.

**Comment by robertahagg** [comment]
Ok Axel, I will fix this.

**Comment by robertahagg** [comment]
@axelolsson I have now fixed models and seeds //Roberta

**Comment by axeberg** [comment]
👍 

LGTM @robertahagg  (that means either Looks Good To Me, or Looking Googd To Merge).

It would've been nice to see it actually be used in some templates in the future, sometime, maybe. :)

**Pull request merged**
